import { SponsorProps } from "@/components/homePages/SponserGrid";

export const PAST_SPONSORS: SponsorProps[] = [
  { name: "Amdocs", image: "/assets/sponsers/amdocs.png",
    className: "col-span-2 row-span-1" 
   },
  { name: "Appwards", image: "/assets/sponsers/appwards.png" },
  { name: "Bingo", image: "/assets/sponsers/bingo.png" },
  { name: "Bitget", image: "/assets/sponsers/bitget.png" },
  { name: "Bond Bazaar", image: "/assets/sponsers/bondbazaarlogo.png" },
  { name: "Bonkers Corner", image: "/assets/sponsers/bonkers_corner.png" },
  { name: "Boult Audio", image: "/assets/sponsers/boult_audio.png" },
  { name: "Bungee", image: "/assets/sponsers/bungee.png" },
  {
    name: "Chief Electoral Officer",
    image: "/assets/sponsers/chief_electoral_officer.png",
    className: "col-span-2 row-span-1",
  },
  { name: "Coca Cola", image: "/assets/sponsers/coca_cola_.png" , className: "col-span-2 row-span-1"},
  { name: "Crispee", image: "/assets/sponsers/crispee.png" },
  { name: "Day Zero", image: "/assets/sponsers/day_zero.png" },
  { name: "Delhi Capitals", image: "/assets/sponsers/delhi_capitals.jpg" },
  { name: "Delhi Tourism", image: "/assets/sponsers/delhi_tourism.png" },
  { name: "EazyDiner", image: "/assets/sponsers/eazydiner.png" },
  { name: "GAIL", image: "/assets/sponsers/gail.png" },
  { name: "Gigabyte", image: "/assets/sponsers/gigabyte.png" },
  { name: "Gold's Gym", image: "/assets/sponsers/gold_s_gym_logo.svg.png" },
  { name: "GrooveNexus", image: "/assets/sponsers/groovenexus.webp" },
  { name: "Hero", image: "/assets/sponsers/hero.png" },
  { name: "Himalaya", image: "/assets/sponsers/himalaya.png" },
  { name: "Hover Robotix", image: "/assets/sponsers/hover_robotix.png" },
  { name: "Instax", image: "/assets/sponsers/instax.png" },
  { name: "Jio Saavn", image: "/assets/sponsers/jio_saavn.png" },
  { name: "Lifelong", image: "/assets/sponsers/lifelong.jpg" },
  { name: "Bauli", image: "/assets/sponsers/logo_bauli.svg__1_.png" },
  { name: "Maltiplai", image: "/assets/sponsers/maltiplai.png" },
  { name: "Max Protein", image: "/assets/sponsers/max_protein.jpg" },
  { name: "Morris Garages", image: "/assets/sponsers/morris_garages.png" },
  { name: "Myntra FWD", image: "/assets/sponsers/myntra_fwd_logo.png" },
  { name: "Next IAS", image: "/assets/sponsers/next_ias.png" },
  { name: "Peck", image: "/assets/sponsers/peck.webp", className: "col-span-2 row-span-2" },
  { name: "Philips", image: "/assets/sponsers/philips.jpg" },
  { name: "Plum Body Lovin'", image: "/assets/sponsers/plum_body_lovin.webp" },
  { name: "Qelica", image: "/assets/sponsers/qelica.png" },
  { name: "Radisson Blu", image: "/assets/sponsers/radisson_blu.png" },
  { name: "Slick", image: "/assets/sponsers/slick.png", className: "col-span-2 row-span-1" },
  { name: "Sparx", image: "/assets/sponsers/sparx.svg" },
  { name: "SSPS Global", image: "/assets/sponsers/ssps_global.jpg" },
  { name: "StockEdge", image: "/assets/sponsers/stockedgelogo.png" },
  { name: "StockGro", image: "/assets/sponsers/stockgro.png" },
  { name: "Storia", image: "/assets/sponsers/storia.png" },
  { name: "Top One Percent", image: "/assets/sponsers/top_one_percent.png" },
  {
    name: "Union Bank of India",
    image: "/assets/sponsers/union_bank_of_india.png",
  },
  { name: "Vision IAS", image: "/assets/sponsers/vision_ias.png" },
  { name: "Wayspire", image: "/assets/sponsers/wayspire.webp" },
  { name: "Web 3 Sabha", image: "/assets/sponsers/web_3_sabha.png" },
  { name: "Xero Degree", image: "/assets/sponsers/xero_degree.png" },
];
