import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";
export const metadata: Metadata = {
  title: "Moksha 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preload" href="/assets/gallery/images/artist1.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist2.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist3.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist4.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist5.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist6.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist7.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist8.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist9.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist10.png" as="image" />
          <link rel="preload" href="/assets/gallery/images/artist11.png" as="image" />
      <body>{children}</body>
      <CustomCursor/>
    </html>
  );
}
